### ISSUE TITLE
Display window

### ISSUE THREAD

**Issue by crosofg** [hpssjellis/easy-tensorflow-on-cloud9#2]
Is it possible to have graphical output? I am getting this error for plt.show()

``````
Traceback (most recent call last):
  File "linear_regression.py", line 73, in <module>
    plt.plot(train_X, train_Y, 'ro', label='Original data')
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 2980, in plot
    ax = gca()
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 803, in gca
    ax =  gcf().gca(**kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 450, in gcf
    return figure()
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 423, in figure
    **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 79, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 87, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1767, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable```
``````

**Comment by hpssjellis** [comment]
Now, I am also out of my depth. Possibly needs to be installed on your local machine as cloud9 would have to initialize some browser based server to show the graphs.

Good luck.
